name: SlapperModels
main: DataLion\SlapperModels\Main
version: 1.0.0
api: 3.15.0
author: DataLion
description: Add Custom Models to Slapper Humans

depend:
 - Slapper

permissions:
 sm.command.setslappermodel:
  default: op
  description: SlapperModel setslappermodel permission
